# Generated by Django 2.2.5 on 2019-09-21 15:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('abstractData', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Data',
            new_name='abstractData',
        ),
    ]
