# Generated by Django 2.2.5 on 2019-09-21 20:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('abstractData', '0003_auto_20190921_2307'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='measurements',
            name='composition',
        ),
        migrations.RemoveField(
            model_name='measurements',
            name='machine',
        ),
        migrations.RemoveField(
            model_name='measurements',
            name='order',
        ),
        migrations.RemoveField(
            model_name='measurements',
            name='parameter',
        ),
        migrations.AlterUniqueTogether(
            name='parameter',
            unique_together=None,
        ),
        migrations.DeleteModel(
            name='Composition',
        ),
        migrations.DeleteModel(
            name='Machine',
        ),
        migrations.DeleteModel(
            name='Measurements',
        ),
        migrations.DeleteModel(
            name='Order',
        ),
        migrations.DeleteModel(
            name='Parameter',
        ),
    ]
